### ISSUE TITLE
Displaying Caption? (Title)

### ISSUE THREAD

**Issue by muppsy007** [DorsetDigital/silverstripe-photoswipe#3]
Hi there. Fantastic module.

I see on the photoswipe library that it supports adding a caption to the image. I'm wondering if there is a way to pump the image Title into this?

```
// slide 1
    {

        src: 'path/to/image1.jpg', // path to image
        w: 1024, // image width
        h: 768, // image height

        msrc: 'path/to/small-image.jpg', // small image placeholder,
                        // main (large) image loads on top of it,
                        // if you skip this parameter - grey rectangle will be displayed,
                        // try to define this property only when small image was loaded before

        title: 'Image Caption'  // used by Default PhotoSwipe UI
                                // if you skip it, there won't be any caption

        // You may add more properties here and use them.
        // For example, demo gallery uses "author" property, which is used in the caption.
        // author: 'John Doe'

    },
```

Also is there a trick to building the js in this extension? I did have a go at adding the above, but I'm not sure how it gets from src to dist.

**Comment by DorsetDigital** [comment]
I'll have a look at the title, shouldn't be too hard to add in.

If you want to replace the JS the module uses, you're better off taking a copy and including a modified version with your own `Requirements` call, then blocking the one from the module.    If you try and run a modified version of the module JS, it will be overwritten whenever the module gets updated.

**Comment by muppsy007** [comment]
Thanks @DorsetDigital. If it helps I hacked a test into a copy of the module that seems to work. One thing with this is it will always show captions using the file title, and some people might not want that due to how files are named. 

Gallery.ss (see added data-caption attribute)
```
<div class="row py-4 picture photogallery" itemscope itemtype="http://schema.org/ImageGallery">
    <% loop $SortedImages %>
        <figure class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
            <% with $ScaleWidth(1024) %>
            <a itemprop="contentUrl" data-size="{$Width}x{$Height}" data-index="$Pos" data-caption="$Title"
               class="progressive replace" data-thumb="$Pad(500,300).URL"
               href="$URL">
                <img src="$Pad(15,9).URL" class="img-fluid img-thumbnail preview"
                     alt="$Top.Title Image"/>
            </a>
            <% end_with %>
        </figure>
    <% end_loop %>
</div>
```

 gallery.js (See $caption var)
```
getItems = function () {
            var items = [];
            $pic.find('a').each(function () {
             var $href = $(this).attr('href'),
                     $size = $(this).data('size').split('x'),
                     $width = $size[0],
                     $height = $size[1],
                     $caption = $(this).data('caption');

             var item = {
              src: $href,
              w: $width,
              h: $height,
              title: $caption
             }

             items.push(item);
            });
            return items;
           }
```
RE: js, I don't really want to replace your JS, but make a change like the above and get it into /dist. Do you use yarn etc? I don't see a package.json in the module and I'm not terribly familiar with how these build processess are supposed to work.

**Comment by DorsetDigital** [comment]
Hi,

I'm just sorting out a release with the new feature.  It will allow you to enable or disable the captions on a per-gallery basis.    I'm just finishing a couple of tests and I'll tag a release.

Cheers
Tim

**Comment by DorsetDigital** [comment]
This should now be covered in the v1.0 stable release.   It should update on packagist shortly.
Shout if you have any issues

**Comment by muppsy007** [comment]
Thanks @DorsetDigital, this is awesome. In our case we always want it on, so for future hunters looking to do the same thing, simply copy the [Gallery.ss template](https://github.com/DorsetDigital/silverstripe-photoswipe/blob/403e326a29030d47b6de510b303390b0f9096aa2/templates/Gallery.ss#L7) to your own /themes/mytheme/tempates directory and remove the `<% if $Up.IncludeTitles == 1 %>` condition or add any custom logic. Just be careful about changing much in this template or you might break the whole gallery.

Thanks again!
